### PR TITLE
Backport of #475 and prepare release 2.1.3

### PR DESCRIPTION
**Pull request by symphony-youri**
- Backport of #475 to 2.1-rc branch
- Bump version to 2.1.3

### CODE REVIEW

**Comment by symphony-elias** [comment]
Shouldn't we ship #474 as well ?

**Comment by symphony-youri** [comment]
> Shouldn't we ship #474 as well ?

👍, I added it

**Review by symphony-elias — APPROVED** [review]
LGTM

**Review by symphony-thibault — APPROVED** [review]
Go for release!

**Pull request merged**
