### PR TITLE
PLAT-10947 Correct migration guide code snippets on documentation

### PR DESCRIPTION
**Pull request by symphony-soufiane**
Generated html code was not rendering correct as the markdown inside html tags was not converted and processed as string. To fix that, we copy the final generated html code in .md file

### Ticket
[PLAT-10947](https://perzoinc.atlassian.net/browse/PLAT-10947)

### CODE REVIEW

**Review by symphony-youri — COMMENTED** [review]
In https://blog.eidinger.info/master-github-markdown-tables-with-multi-line-code-blocks they mention having an empty line before and after the code blocks, maybe worth trying?

Because having the code as html like this makes it very difficult to read when a text editor is used (and to maintain)

**Comment by symphony-elias** [comment]
> https://blog.eidinger.info/master-github-markdown-tables-with-multi-line-code-blocks

@symphony-soufiane already tried if I'm not mistaken. Rendering is OK on GH UI ( https://github.com/finos/symphony-bdk-java/blob/main/docs/migration.md ) but not in GH pages ( https://symphony-bdk-java.finos.org/migration.html ) and I don't know why

**Comment by symphony-thibault** [comment]
@symphony-soufiane could https://idratherbewriting.com/documentation-theme-jekyll/mydoc_tables.html#htmltables work?

**Comment by symphony-soufiane** [comment]
> @symphony-soufiane could https://idratherbewriting.com/documentation-theme-jekyll/mydoc_tables.html#htmltables work?

Didn't work neither, here's the rendering:

markdown-span

**Comment by symphony-soufiane** [comment]
Rendering can be verified on [https://symphony-soufiane.github.io/symphony-bdk-java/migration.html](https://symphony-soufiane.github.io/symphony-bdk-java/migration.html)

My fork is configured to generate documentation from this PR, check this here ([https://github.com/symphony-soufiane/symphony-bdk-java/settings/pages](https://github.com/symphony-soufiane/symphony-bdk-java/settings/pages))

**Review by symphony-youri — APPROVED** [review]

**Review by symphony-elias — APPROVED** [review]

**Pull request merged**
