### PR TITLE
PLAT-10897 PLAT-10898 fix Jersey and Commons dependencies in Legacy

### PR DESCRIPTION
**Pull request by symphony-soufiane**
### Ticket
[#523](https://github.com/finos/symphony-bdk-java/issues/523)

### Description
Upgraded jersey dependency to 2.34 and Commons to 2.7

### CODE REVIEW

**Comment by symphony-youri** [comment]
Do we want to keep updating the legacy BDK? Were there specific vulnerabilities associated to those dependencies?

**Comment by symphony-soufiane** [comment]
> Do we want to keep updating the legacy BDK? Were there specific vulnerabilities associated to those dependencies?

Some of our customers are still using the legacy BDK, that's why we were asked to do the fix here.

**Review by symphony-youri — APPROVED** [review]

**Comment by anthony-symphony** [comment]
@symphony-soufiane any particular reason we are only going to commons-io 2.7 instead of going straight to 2.8?

**Comment by symphony-soufiane** [comment]
> @symphony-soufiane any particular reason we are only going to commons-io 2.7 instead of going straight to 2.8?

@anthony-symphony it was corrected to 2.8.0 in a later commit.

**Pull request merged**
